package other.hht.product;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-10-20T11:39:47.718+08:00
 * Generated source version: 3.2.14
 *
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZFM_CRM_CPBM")
@XmlSeeAlso({ObjectFactory.class})
public interface ZFMCRMCPBM {

    @WebMethod(operationName = "ZfmCrmCpbm")
    @RequestWrapper(localName = "ZfmCrmCpbm", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "other.hht.product.ZfmCrmCpbm_Type")
    @ResponseWrapper(localName = "ZfmCrmCpbmResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "other.hht.product.ZfmCrmCpbmResponse")
    public void zfmCrmCpbm(
        @WebParam(mode = WebParam.Mode.INOUT, name = "EtMatnr", targetNamespace = "")
        javax.xml.ws.Holder<TableOfZfgCrmMatnrS> etMatnr,
        @WebParam(name = "IFlag", targetNamespace = "")
        java.lang.String iFlag
    );
}
