package other.hht.bank;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2020-09-01T13:46:03.471+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebServiceClient(name = "ZFM_CRM_BNKA", 
                  wsdlLocation = "https://nothingedu.oss-cn-beijing.aliyuncs.com/bank.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style") 
public class ZFMCRMBNKA_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFM_CRM_BNKA");
    public final static QName Binding = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding");
    public final static QName BindingSOAP12 = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding_SOAP12");
    static {
        URL url = null;
        try {
            url = new URL("https://nothingedu.oss-cn-beijing.aliyuncs.com/bank.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZFMCRMBNKA_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://nothingedu.oss-cn-beijing.aliyuncs.com/bank.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZFMCRMBNKA_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZFMCRMBNKA_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZFMCRMBNKA_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZFMCRMBNKA_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZFMCRMBNKA_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZFMCRMBNKA_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ZFMCRMBNKA
     */
    @WebEndpoint(name = "binding")
    public ZFMCRMBNKA getBinding() {
        return super.getPort(Binding, ZFMCRMBNKA.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFMCRMBNKA
     */
    @WebEndpoint(name = "binding")
    public ZFMCRMBNKA getBinding(WebServiceFeature... features) {
        return super.getPort(Binding, ZFMCRMBNKA.class, features);
    }
    /**
     *
     * @return
     *     returns ZFMCRMBNKA
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZFMCRMBNKA getBindingSOAP12() {
        return super.getPort(BindingSOAP12, ZFMCRMBNKA.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFMCRMBNKA
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZFMCRMBNKA getBindingSOAP12(WebServiceFeature... features) {
        return super.getPort(BindingSOAP12, ZFMCRMBNKA.class, features);
    }

}
