package other.hht.bank;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2020-09-01T13:46:03.465+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZFM_CRM_BNKA")
@XmlSeeAlso({ObjectFactory.class})
public interface ZFMCRMBNKA {

    @WebMethod(operationName = "ZfmCrmBnka")
    @RequestWrapper(localName = "ZfmCrmBnka", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "other.hht.bank.ZfmCrmBnka_Type")
    @ResponseWrapper(localName = "ZfmCrmBnkaResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "other.hht.bank.ZfmCrmBnkaResponse")
    public void zfmCrmBnka(
            @WebParam(mode = WebParam.Mode.INOUT, name = "TBnka", targetNamespace = "")
                    javax.xml.ws.Holder<TableOfZsrmBnka> tBnka
    );
}
