
package other.hht.contract;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-11-03T19:48:52.489+08:00
 * Generated source version: 3.2.14
 *
 */
public final class ZFMCRMCONTRACTM_BindingSOAP12_Client {

    private static final QName SERVICE_NAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFM_CRM_CONTRACT_M");

    private ZFMCRMCONTRACTM_BindingSOAP12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ZFMCRMCONTRACTM_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ZFMCRMCONTRACTM_Service ss = new ZFMCRMCONTRACTM_Service(wsdlURL, SERVICE_NAME);
        ZFMCRMCONTRACTM port = ss.getBindingSOAP12();

        {
        System.out.println("Invoking zfmCrmContractM...");
        java.lang.String _zfmCrmContractM_iFlag = "";
        other.hht.contract.ZcrmContractIs _zfmCrmContractM_isContract = null;
        other.hht.contract.ZcrmContractOt _zfmCrmContractM_itContractVal = null;
        javax.xml.ws.Holder<other.hht.contract.ZcrmContractOt> _zfmCrmContractM_itContract = new javax.xml.ws.Holder<other.hht.contract.ZcrmContractOt>(_zfmCrmContractM_itContractVal);
        javax.xml.ws.Holder<other.hht.contract.ZcrmMessgS> _zfmCrmContractM_esMessg = new javax.xml.ws.Holder<other.hht.contract.ZcrmMessgS>();
        port.zfmCrmContractM(_zfmCrmContractM_iFlag, _zfmCrmContractM_isContract, _zfmCrmContractM_itContract, _zfmCrmContractM_esMessg);

        System.out.println("zfmCrmContractM._zfmCrmContractM_itContract=" + _zfmCrmContractM_itContract.value);
        System.out.println("zfmCrmContractM._zfmCrmContractM_esMessg=" + _zfmCrmContractM_esMessg.value);

        }

        System.exit(0);
    }

}
