package other.hht.contract;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-11-03T19:48:52.499+08:00
 * Generated source version: 3.2.14
 *
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZFM_CRM_CONTRACT_M")
@XmlSeeAlso({ObjectFactory.class})
public interface ZFMCRMCONTRACTM {

    @WebMethod(operationName = "ZfmCrmContractM")
    @RequestWrapper(localName = "ZfmCrmContractM", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "other.hht.contract.ZfmCrmContractM_Type")
    @ResponseWrapper(localName = "ZfmCrmContractMResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "other.hht.contract.ZfmCrmContractMResponse")
    public void zfmCrmContractM(
        @WebParam(name = "IFlag", targetNamespace = "")
        java.lang.String iFlag,
        @WebParam(name = "IsContract", targetNamespace = "")
        other.hht.contract.ZcrmContractIs isContract,
        @WebParam(mode = WebParam.Mode.INOUT, name = "ItContract", targetNamespace = "")
        javax.xml.ws.Holder<ZcrmContractOt> itContract,
        @WebParam(mode = WebParam.Mode.OUT, name = "EsMessg", targetNamespace = "")
        javax.xml.ws.Holder<ZcrmMessgS> esMessg
    );
}
