package other.hht.contract;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-11-03T19:48:52.505+08:00
 * Generated source version: 3.2.14
 *
 */
@WebServiceClient(name = "ZFM_CRM_CONTRACT_M",
                  wsdlLocation = "file:/c:/test/contract.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class ZFMCRMCONTRACTM_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFM_CRM_CONTRACT_M");
    public final static QName Binding = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding");
    public final static QName BindingSOAP12 = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding_SOAP12");
    static {
        URL url = null;
        try {
            url = new URL("file:/c:/test/contract.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZFMCRMCONTRACTM_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/c:/test/contract.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZFMCRMCONTRACTM_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZFMCRMCONTRACTM_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZFMCRMCONTRACTM_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ZFMCRMCONTRACTM_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZFMCRMCONTRACTM_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZFMCRMCONTRACTM_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ZFMCRMCONTRACTM
     */
    @WebEndpoint(name = "binding")
    public ZFMCRMCONTRACTM getBinding() {
        return super.getPort(Binding, ZFMCRMCONTRACTM.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFMCRMCONTRACTM
     */
    @WebEndpoint(name = "binding")
    public ZFMCRMCONTRACTM getBinding(WebServiceFeature... features) {
        return super.getPort(Binding, ZFMCRMCONTRACTM.class, features);
    }


    /**
     *
     * @return
     *     returns ZFMCRMCONTRACTM
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZFMCRMCONTRACTM getBindingSOAP12() {
        return super.getPort(BindingSOAP12, ZFMCRMCONTRACTM.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFMCRMCONTRACTM
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZFMCRMCONTRACTM getBindingSOAP12(WebServiceFeature... features) {
        return super.getPort(BindingSOAP12, ZFMCRMCONTRACTM.class, features);
    }

}
