
package other.hht.extmber;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-10-23T18:44:14.420+08:00
 * Generated source version: 3.2.14
 *
 */
public final class ZFMCRMTAOJLIST_Binding_Client {

    private static final QName SERVICE_NAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFM_CRM_TAOJLIST");

    private ZFMCRMTAOJLIST_Binding_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ZFMCRMTAOJLIST_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ZFMCRMTAOJLIST_Service ss = new ZFMCRMTAOJLIST_Service(wsdlURL, SERVICE_NAME);
        ZFMCRMTAOJLIST port = ss.getBinding();

        {
        System.out.println("Invoking zfmCrmTaojlist...");
        java.lang.String _zfmCrmTaojlist_iMatnr = "";
        other.hht.extmber.ZcrmIdnrkT _zfmCrmTaojlist__return = port.zfmCrmTaojlist(_zfmCrmTaojlist_iMatnr);
        System.out.println("zfmCrmTaojlist.result=" + _zfmCrmTaojlist__return);


        }

        System.exit(0);
    }

}
