package other.hht.matnr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-10-23T18:44:28.738+08:00
 * Generated source version: 3.2.14
 *
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZFM_CRM_MATNR_TJ")
@XmlSeeAlso({ObjectFactory.class})
public interface ZFMCRMMATNRTJ {

    @WebMethod(operationName = "ZfmCrmMatnrTj")
    @RequestWrapper(localName = "ZfmCrmMatnrTj", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "other.hht.matnr.ZfmCrmMatnrTj_Type")
    @ResponseWrapper(localName = "ZfmCrmMatnrTjResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "other.hht.matnr.ZfmCrmMatnrTjResponse")
    public void zfmCrmMatnrTj(
        @WebParam(mode = WebParam.Mode.INOUT, name = "EtItem", targetNamespace = "")
        javax.xml.ws.Holder<TableOfZcrmMatnrTjS1> etItem,
        @WebParam(name = "ICpbm", targetNamespace = "")
        java.lang.String iCpbm
    );
}
