
package other.hht.matnr;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-10-23T18:44:28.698+08:00
 * Generated source version: 3.2.14
 *
 */
public final class ZFMCRMMATNRTJ_Binding_Client {

    private static final QName SERVICE_NAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFM_CRM_MATNR_TJ");

    private ZFMCRMMATNRTJ_Binding_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ZFMCRMMATNRTJ_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ZFMCRMMATNRTJ_Service ss = new ZFMCRMMATNRTJ_Service(wsdlURL, SERVICE_NAME);
        ZFMCRMMATNRTJ port = ss.getBinding();

        {
        System.out.println("Invoking zfmCrmMatnrTj...");
        other.hht.matnr.TableOfZcrmMatnrTjS1 _zfmCrmMatnrTj_etItemVal = null;
        javax.xml.ws.Holder<other.hht.matnr.TableOfZcrmMatnrTjS1> _zfmCrmMatnrTj_etItem = new javax.xml.ws.Holder<other.hht.matnr.TableOfZcrmMatnrTjS1>(_zfmCrmMatnrTj_etItemVal);
        java.lang.String _zfmCrmMatnrTj_iCpbm = "";
        port.zfmCrmMatnrTj(_zfmCrmMatnrTj_etItem, _zfmCrmMatnrTj_iCpbm);

        System.out.println("zfmCrmMatnrTj._zfmCrmMatnrTj_etItem=" + _zfmCrmMatnrTj_etItem.value);

        }

        System.exit(0);
    }

}
