package other.hht.logistics;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-11-02T20:17:37.060+08:00
 * Generated source version: 3.2.14
 *
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZFM_CRM_LGCS_P")
@XmlSeeAlso({ObjectFactory.class})
public interface ZFMCRMLGCSP {

    @WebMethod(operationName = "ZfmCrmLgcsP")
    @RequestWrapper(localName = "ZfmCrmLgcsP", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "other.hht.logistics.ZfmCrmLgcsP_Type")
    @ResponseWrapper(localName = "ZfmCrmLgcsPResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "other.hht.logistics.ZfmCrmLgcsPResponse")
    public void zfmCrmLgcsP(
        @WebParam(name = "IFlag", targetNamespace = "")
        java.lang.String iFlag,
        @WebParam(name = "IsHead", targetNamespace = "")
        other.hht.logistics.ZcrmOutpi1S isHead,
        @WebParam(name = "ItGoods", targetNamespace = "")
        other.hht.logistics.ZcrmOutpi3T itGoods,
        @WebParam(name = "ItGuiji", targetNamespace = "")
        other.hht.logistics.ZcrmOutpi2T itGuiji,
        @WebParam(name = "ItXgwld", targetNamespace = "")
        other.hht.logistics.ZcrmOutpi4T itXgwld,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtOutpo1", targetNamespace = "")
        javax.xml.ws.Holder<ZcrmOutpo1T> etOutpo1,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtOutpo2", targetNamespace = "")
        javax.xml.ws.Holder<ZcrmOutpo2T> etOutpo2,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtOutpo3", targetNamespace = "")
        javax.xml.ws.Holder<ZcrmOutpo3T> etOutpo3,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtOutpo4", targetNamespace = "")
        javax.xml.ws.Holder<ZcrmOutpo4T> etOutpo4
    );
}
