
package other.hht.product;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-10-20T11:39:47.677+08:00
 * Generated source version: 3.2.14
 *
 */
public final class ZFMCRMCPBM_Binding_Client {

    private static final QName SERVICE_NAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFM_CRM_CPBM");

    private ZFMCRMCPBM_Binding_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ZFMCRMCPBM_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ZFMCRMCPBM_Service ss = new ZFMCRMCPBM_Service(wsdlURL, SERVICE_NAME);
        ZFMCRMCPBM port = ss.getBinding();

        {
        System.out.println("Invoking zfmCrmCpbm...");
        other.hht.product.TableOfZfgCrmMatnrS _zfmCrmCpbm_etMatnrVal = null;
        javax.xml.ws.Holder<other.hht.product.TableOfZfgCrmMatnrS> _zfmCrmCpbm_etMatnr = new javax.xml.ws.Holder<other.hht.product.TableOfZfgCrmMatnrS>(_zfmCrmCpbm_etMatnrVal);
        java.lang.String _zfmCrmCpbm_iFlag = "";
        port.zfmCrmCpbm(_zfmCrmCpbm_etMatnr, _zfmCrmCpbm_iFlag);

        System.out.println("zfmCrmCpbm._zfmCrmCpbm_etMatnr=" + _zfmCrmCpbm_etMatnr.value);

        }

        System.exit(0);
    }

}
