package other.logistics.manager;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-11-03T18:45:24.027+08:00
 * Generated source version: 3.2.14
 *
 */
@WebServiceClient(name = "ZFM_CRM_LGCS_D",
                  wsdlLocation = "https://nothingedu.oss-cn-beijing.aliyuncs.com/lgsticManager.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class ZFMCRMLGCSD_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFM_CRM_LGCS_D");
    public final static QName Binding = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding");
    public final static QName BindingSOAP12 = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "binding_SOAP12");
    static {
        URL url = null;
        try {
            url = new URL("https://nothingedu.oss-cn-beijing.aliyuncs.com/lgsticManager.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZFMCRMLGCSD_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://nothingedu.oss-cn-beijing.aliyuncs.com/lgsticManager.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZFMCRMLGCSD_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZFMCRMLGCSD_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZFMCRMLGCSD_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ZFMCRMLGCSD_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZFMCRMLGCSD_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZFMCRMLGCSD_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ZFMCRMLGCSD
     */
    @WebEndpoint(name = "binding")
    public ZFMCRMLGCSD getBinding() {
        return super.getPort(Binding, ZFMCRMLGCSD.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFMCRMLGCSD
     */
    @WebEndpoint(name = "binding")
    public ZFMCRMLGCSD getBinding(WebServiceFeature... features) {
        return super.getPort(Binding, ZFMCRMLGCSD.class, features);
    }


    /**
     *
     * @return
     *     returns ZFMCRMLGCSD
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZFMCRMLGCSD getBindingSOAP12() {
        return super.getPort(BindingSOAP12, ZFMCRMLGCSD.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZFMCRMLGCSD
     */
    @WebEndpoint(name = "binding_SOAP12")
    public ZFMCRMLGCSD getBindingSOAP12(WebServiceFeature... features) {
        return super.getPort(BindingSOAP12, ZFMCRMLGCSD.class, features);
    }

}
