package other.logistics.manager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-11-03T18:45:24.022+08:00
 * Generated source version: 3.2.14
 *
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZFM_CRM_LGCS_D")
@XmlSeeAlso({ObjectFactory.class})
public interface ZFMCRMLGCSD {

    @WebMethod(operationName = "ZfmCrmLgcsD")
    @RequestWrapper(localName = "ZfmCrmLgcsD", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "other.logistics.manager.ZfmCrmLgcsD_Type")
    @ResponseWrapper(localName = "ZfmCrmLgcsDResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "other.logistics.manager.ZfmCrmLgcsDResponse")
    public void zfmCrmLgcsD(
        @WebParam(name = "IFlag", targetNamespace = "")
        java.lang.String iFlag,
        @WebParam(name = "IsHead", targetNamespace = "")
        other.logistics.manager.ZcrmOutdiS isHead,
        @WebParam(name = "ItItem", targetNamespace = "")
        other.logistics.manager.ZcrmOutdmT itItem,
        @WebParam(mode = WebParam.Mode.OUT, name = "EsMessg", targetNamespace = "")
        javax.xml.ws.Holder<ZcrmMessgS> esMessg,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtOutdo", targetNamespace = "")
        javax.xml.ws.Holder<ZcrmOutdoT> etOutdo
    );
}
