
package other.hht.bank;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2020-11-03T11:15:54.605+08:00
 * Generated source version: 3.2.14
 *
 */
public final class ZFMCRMBNKA_Binding_Client {

    private static final QName SERVICE_NAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZFM_CRM_BNKA");

    private ZFMCRMBNKA_Binding_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ZFMCRMBNKA_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ZFMCRMBNKA_Service ss = new ZFMCRMBNKA_Service(wsdlURL, SERVICE_NAME);
        ZFMCRMBNKA port = ss.getBinding();

        {
        System.out.println("Invoking zfmCrmBnka...");
        other.hht.bank.TableOfZssrmBnka _zfmCrmBnka_tBnkaVal = null;
        javax.xml.ws.Holder<other.hht.bank.TableOfZssrmBnka> _zfmCrmBnka_tBnka = new javax.xml.ws.Holder<other.hht.bank.TableOfZssrmBnka>(_zfmCrmBnka_tBnkaVal);
        port.zfmCrmBnka(_zfmCrmBnka_tBnka);

        System.out.println("zfmCrmBnka._zfmCrmBnka_tBnka=" + _zfmCrmBnka_tBnka.value);

        }

        System.exit(0);
    }

}
